myproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from .views import AllProductsListView, ProductListView, ProductDetailView

app_name = 'shop'

urlpatterns = [
    path('', AllProductsListView.as_view(), name='product_list'),  # <- ეს
    path('category/<slug:slug>/', ProductListView.as_view(), name='product_list_by_category'),
    path('', AllProductsListView.as_view(), name='all_products'),
    path('product/<int:id>/', ProductDetailView.as_view(), name='product_detail'),
]

shop/models.py
from django.db import models
from django.utils import timezone


class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ['name']
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)  # ეს უნდა გქონდეს!
    stock = models.PositiveIntegerField(default=0)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)

    def __str__(self):
        return self.name

shop/forms.py
from django import forms
from .models import Product

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'price', 'category']

shop/views.py
from django.views.generic import ListView, DetailView, CreateView
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from .models import Category, Product
from .forms import ProductForm 
class AllProductsListView(ListView):
    model = Product
    template_name = 'shop/all_products.html'
    context_object_name = 'products'
class ProductListView(ListView):
    model = Product
    template_name = 'shop/product_list.html'
    context_object_name = 'products'

    def get_queryset(self):
        return Product.objects.filter(category__slug=self.kwargs.get('slug'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = get_object_or_404(Category, slug=self.kwargs.get('slug'))
        return context



from django.shortcuts import get_object_or_404
from django.views.generic import DetailView
from .models import Product

class ProductDetailView(DetailView):
    model = Product
    template_name = 'shop/product_detail.html'

    def get_object(self):
        return get_object_or_404(Product, id=self.kwargs['id'])

class ProductCreateView(CreateView):
    model = Product
    template_name = 'shop/product_add.html'
    form_class = ProductForm

    def get_success_url(self):
        return self.object.get_absolute_url()


from .forms import ProductForm

class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'shop/product_add.html'

shop/templates/shop/all_products.html
{% extends "shop/base.html" %}

{% block title %}All Products{% endblock %}
{% block content %}
<h1 class="mb-4">All Products</h1>
<div class="row">
    {% for product in object_list %}
        <div class="col-md-4 mb-4">
            <div class="card h-100">
                {% if product.image %}
                    <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.name }}">
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title">{{ product.name }}</h5>
                    <p class="card-text">{{ product.description|truncatechars:100 }}</p>
                    <a href="{% url 'shop:product_detail' product.pk %}" class="btn btn-primary">View Details</a>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock %}

shop/templates/shop/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}My Shop{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="{% url 'shop:all_products' %}">MyShop</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarNav" aria-controls="navbarNav"
            aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</nav>

<div class="container mt-4">
    {% block content %}{% endblock %}
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

shop/templates/shop/category_list.html
{% extends 'shop/base.html' %}
{% block title %}Categories{% endblock %}

{% block content %}
<h1>Categories</h1>
<ul class="list-group">
    {% for category in categories %}
        <li class="list-group-item">
            <a href="{% url 'shop:product_list_by_category' slug=category.slug %}">{{ category.name }}</a>
        </li>
    {% endfor %}
</ul>
{% endblock %}

shop/templates/shop/product_detail.html
{% extends "shop/base.html" %}

{% block title %}{{ object.name }}{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-6">
        {% if object.image %}
            <img src="{{ object.image.url }}" class="img-fluid" alt="{{ object.name }}">
        {% endif %}
    </div>
    <div class="col-md-6">
        <h2>{{ object.name }}</h2>
        <p>{{ object.description }}</p>
        <p><strong>Stock:</strong> {{ object.stock }}</p>
        <p><strong>Available:</strong> {{ object.available }}</p>
    </div>
</div>
{% endblock %}

shop/templates/shop/product_form.html
{% extends "shop/base.html" %}

{% block title %}Add/Edit Product{% endblock %}
{% block content %}
<h2>Add / Edit Product</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
        <div class="mb-3">
            {{ field.label_tag }}
            {{ field }}
            {% if field.errors %}
                <div class="text-danger">{{ field.errors }}</div>
            {% endif %}
        </div>
    {% endfor %}
    <button type="submit" class="btn btn-success">Save</button>
</form>
{% endblock %}

shop/templates/shop/product_list.html
{% extends 'shop/base.html' %}
{% block title %}Products in {{ category.name }}{% endblock %}

{% block content %}
<h2>Products in {{ category.name }}</h2>
<ul class="list-group">
    {% for product in products %}
        <li class="list-group-item">
            <a href="{{ product.get_absolute_url }}">{{ product.name }}</a> - ${{ product.price }}
        </li>
    {% endfor %}
</ul>
{% endblock %}